
runtime: nodejs
env: flex
manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    static_files: view/build/index.html
    upload: view/build/index.html
  - url: /
    static_dir: view/build
